### ISSUE TITLE
Needs testing/fixing on Linux.

### ISSUE THREAD

**Issue by skitzoid** [skitzoid/Box2D-MT#2]
Eventually.

**Comment by bog2k3** [comment]
I have tested it on Linux for quite a while (almost a year now) and everything's fine, apart from a minor build issue which I've fixed (see the pull request).
Another issue (which original Box2D has as well) is it crashes or hangs randomly if you have some really small fixtures in the world (i am working around this by putting not creating fixtures smaller than b2_linearSlop).
Multi-threading-wise, great job, it really works well.
